<a href="https://colab.research.google.com/github/sardear/TorchNN/blob/main/TorchNN_nnModule.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Module定义所有neural network基本形态，所有的网络架构都继承此形态。

```
import torch.nn as nn
import torch.nn.functional as F

class Model(nn.Module):
  def __init__(self):
    super().__init__()
    # 此处定义所有功能，也就是可能会用到的架构

  def forward(self, x):
    # 执行Model时会执行此处内容，也就是网络真正执行的顺序
    # 此处定义所需的CNN的squence
    return 
```
注：必须要有`super().__init__()`，才会继承nn.Module

In [2]:
import torch
import torch.nn as nn

class Net(nn.Module):

  def __init__(self,num_class=10):
    super().__init__()
    self.features = nn.Sequential(
        nn.Conv2d(in_channels=3,out_channels=6,kernel_size=3),
        nn.BatchNorm2d(6),
        nn.ReLU(inplace=True),
        nn.MaxPool2d(kernel_size=2,stride=2),
        nn.Conv2d(in_channels=6,out_channels=9,kernel_size=3),
        nn.BatchNorm2d(9),
        nn.ReLU(inplace=True),
        nn.MaxPool2d(kernel_size=2,stride=2)
        )
    
    self.classifier = nn.Sequential(
        nn.Linear(9*8*8,128),
        nn.ReLU(inplace=True),
        nn.Dropout(),
        nn.Linear(128,num_class)
        # 注意这里没有softmax
        )

def forward(self,x):
  output = self.features(x)
  output = output.view(output.size()[0],-1)
  output = self.classifier(output)

  return output

In [3]:
model = Net()
print(model)

Net(
  (features): Sequential(
    (0): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1))
    (1): BatchNorm2d(6, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(6, 9, kernel_size=(3, 3), stride=(1, 1))
    (5): BatchNorm2d(9, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU(inplace=True)
    (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (classifier): Sequential(
    (0): Linear(in_features=576, out_features=128, bias=True)
    (1): ReLU(inplace=True)
    (2): Dropout(p=0.5, inplace=False)
    (3): Linear(in_features=128, out_features=10, bias=True)
  )
)


In [4]:
modules = model.modules()
for m in modules:
  print(m)

Net(
  (features): Sequential(
    (0): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1))
    (1): BatchNorm2d(6, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(6, 9, kernel_size=(3, 3), stride=(1, 1))
    (5): BatchNorm2d(9, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU(inplace=True)
    (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (classifier): Sequential(
    (0): Linear(in_features=576, out_features=128, bias=True)
    (1): ReLU(inplace=True)
    (2): Dropout(p=0.5, inplace=False)
    (3): Linear(in_features=128, out_features=10, bias=True)
  )
)
Sequential(
  (0): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1))
  (1): BatchNorm2d(6, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU(inplace=True)
  (3): MaxPool2d(kernel_size=2, stride=2, paddin

In [9]:
print("Children:")
children = model.children() #回传所有子modules
for child in children:
  print(child)

Children:
Sequential(
  (0): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1))
  (1): BatchNorm2d(6, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (2): ReLU(inplace=True)
  (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (4): Conv2d(6, 9, kernel_size=(3, 3), stride=(1, 1))
  (5): BatchNorm2d(9, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (6): ReLU(inplace=True)
  (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
)
Sequential(
  (0): Linear(in_features=576, out_features=128, bias=True)
  (1): ReLU(inplace=True)
  (2): Dropout(p=0.5, inplace=False)
  (3): Linear(in_features=128, out_features=10, bias=True)
)


In [12]:
## Module:methods
import torchvision
model = torchvision.models.resnet18()
print(model)
# get submodule
sub_modules = model.get_submodule('layer1')
print() # 打印空行
print("Layer 1:", sub_modules)
# get layer1, 0th basic block, conv1
layer1_0_conv1 = model.get_submodule('layer1.0.conv1')
print()
print("layer1_conv1:", layer1_0_conv1)

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [16]:
# import torch
# from torch.nn.parameter import Parameter
# def get_parameter(self,target:str)->"Parameter":
#   module_path,_,param_name = target.rpartition(".")
#   mod:torch.nn.Module = self.get_submodule(module_path)
#   if not hasattr(mod,param_name):
#     raise AttributeError(mod._get_name()+" has no attribute" + param_name + "`")
#   param: torch.nn.Parameter = getattr(mod,param_name)
#   if not isinstance(param,torch.nn.Parameter):
#     raise AttributeError("`"+ param_name + "` is not an " "nn.Parameter")
#   return param

# get_parameter
param = model.get_parameter('conv1.weight')
print(param)

Parameter containing:
tensor([[[[-1.8988e-03, -2.8773e-02,  3.8315e-02,  ...,  4.4257e-02,
           -8.1411e-03, -4.9721e-03],
          [-1.8315e-02,  6.4283e-03,  2.4338e-02,  ..., -3.6286e-02,
           -3.3642e-02,  3.6314e-02],
          [ 4.1847e-02,  3.0720e-02, -4.4204e-02,  ...,  4.7191e-02,
            1.5107e-02, -2.2461e-02],
          ...,
          [ 3.3605e-02, -2.9649e-02, -2.6165e-02,  ..., -1.7436e-02,
            9.2753e-03,  1.5277e-02],
          [ 3.0923e-02, -1.4630e-02,  2.9526e-02,  ..., -2.2166e-02,
           -4.1855e-02,  7.0035e-02],
          [ 4.3775e-02, -1.9033e-03, -2.4081e-02,  ...,  5.4472e-02,
           -3.2067e-02, -1.1802e-02]],

         [[ 1.1715e-02,  1.5475e-02, -3.1956e-02,  ...,  2.7717e-02,
            1.9253e-02, -1.0844e-02],
          [ 6.6813e-03, -4.6861e-02,  3.8394e-02,  ..., -1.3066e-03,
           -1.8528e-02,  2.8178e-03],
          [ 3.9697e-02,  3.9541e-02,  3.2296e-02,  ...,  4.7676e-03,
            2.8595e-03,  6.3041e-03]

In [29]:
## Method:named children()
# 取回module及其name
import torchvision
model = torchvision.models.resnet18()
# import structure_alexnet
# model = structure_alexnet.Structure_AlexNet()
# get whole model's children and name
named_module = model.named_children()
print(named_module) #has dict
for name,module in named_module:
  print()
  print("Name:",name,"Module:",module)
# get submodule:feature extraction
sub_module = model.get_submodule("layer1")
# get submodule's children and name
named_module = sub_module.named_children()
for name,module in named_module:
  print('================================================')
  print("Name:",name,"Module:",module)

<generator object Module.named_children at 0x7f4c04fe4120>

Name: conv1 Module: Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)

Name: bn1 Module: BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)

Name: relu Module: ReLU(inplace=True)

Name: maxpool Module: MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)

Name: layer1 Module: Sequential(
  (0): BasicBlock(
    (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (1): BasicBlock(
    (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentu

In [32]:
## Method:Module.parameters()
model = Net()
print(model)
# use parameter to get model's parameter
# get submodel
conv_layer1 = model.get_submodule("features.0")
params = conv_layer1.parameters()
for param in params:
  print()
  print(param)

Net(
  (features): Sequential(
    (0): Conv2d(3, 6, kernel_size=(3, 3), stride=(1, 1))
    (1): BatchNorm2d(6, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (4): Conv2d(6, 9, kernel_size=(3, 3), stride=(1, 1))
    (5): BatchNorm2d(9, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU(inplace=True)
    (7): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (classifier): Sequential(
    (0): Linear(in_features=576, out_features=128, bias=True)
    (1): ReLU(inplace=True)
    (2): Dropout(p=0.5, inplace=False)
    (3): Linear(in_features=128, out_features=10, bias=True)
  )
)

Parameter containing:
tensor([[[[ 1.7785e-01,  8.1111e-02,  3.0277e-02],
          [-1.2621e-01, -8.7878e-03,  1.5762e-01],
          [-6.8628e-02,  1.5327e-01,  4.9181e-02]],

         [[ 1.7093e-01, -2.1703e-03, -5.9800e-02]

In [33]:
params = conv_layer1.named_parameters()
for name,param in params: #dict
  print(name)
  print(param)

weight
Parameter containing:
tensor([[[[ 1.7785e-01,  8.1111e-02,  3.0277e-02],
          [-1.2621e-01, -8.7878e-03,  1.5762e-01],
          [-6.8628e-02,  1.5327e-01,  4.9181e-02]],

         [[ 1.7093e-01, -2.1703e-03, -5.9800e-02],
          [ 9.2604e-02,  4.4520e-02, -6.2389e-02],
          [-1.7966e-01, -1.6981e-01, -4.1207e-02]],

         [[-1.2941e-01, -3.9010e-02, -1.7734e-04],
          [ 3.1408e-02,  1.7166e-01,  4.9059e-02],
          [-1.3413e-01,  1.7533e-01, -8.1339e-02]]],


        [[[ 1.2514e-01,  2.7444e-02,  3.9024e-02],
          [ 6.8653e-02, -4.8503e-02,  8.9417e-02],
          [ 8.5959e-02, -1.4984e-01, -3.4734e-02]],

         [[-1.3673e-01, -9.3213e-02, -1.7136e-01],
          [-1.4136e-01, -9.3440e-02, -6.8205e-02],
          [ 1.2339e-01, -5.6089e-03,  8.0067e-02]],

         [[-7.8148e-02,  1.7063e-01, -8.8452e-02],
          [ 1.0680e-01,  5.3696e-02, -7.1251e-02],
          [ 3.6059e-02, -3.6995e-02,  3.3390e-02]]],


        [[[ 5.9600e-02, -1.6356e-01, 

In [34]:
## method:state dict
## save model的常用方式
model = Net()
# print(model.state_dict()) #给出所有name,weight(OrderedDict)
conv_layer = model.get_submodule("features.0")
print(conv_layer.state_dict()) #给出0:conv2d这一层的OrderedDict

OrderedDict([('weight', tensor([[[[ 0.1408, -0.1603,  0.0644],
          [-0.1371,  0.1248,  0.0881],
          [ 0.0815,  0.0827, -0.1724]],

         [[ 0.1478, -0.0850,  0.1286],
          [ 0.0490,  0.0538,  0.0535],
          [-0.1918,  0.1021,  0.0917]],

         [[ 0.1080, -0.0810, -0.0904],
          [-0.0020, -0.0103, -0.0975],
          [ 0.0336, -0.0677, -0.0840]]],


        [[[ 0.0167, -0.0627,  0.1662],
          [ 0.0351, -0.0121, -0.0504],
          [ 0.1028, -0.1285, -0.0055]],

         [[ 0.1053,  0.0680, -0.0640],
          [ 0.1791,  0.0275,  0.1874],
          [ 0.0898, -0.1500, -0.1204]],

         [[ 0.0822,  0.0997,  0.0246],
          [-0.1247,  0.1848, -0.1403],
          [ 0.0923,  0.0632,  0.1804]]],


        [[[ 0.0767, -0.0585, -0.1072],
          [-0.0876, -0.1102, -0.0114],
          [-0.0232, -0.1273,  0.1346]],

         [[-0.0588, -0.1576, -0.1286],
          [ 0.1399,  0.0780,  0.0194],
          [-0.1379,  0.0785,  0.1636]],

         [[-0.0696, 