<a href="https://colab.research.google.com/github/sardear/TorchNN/blob/main/TorchNN_LinearLayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Applies a linear transformation to the incoming data:
$y=x A^{T}+b$

In [7]:
## Linear Layer
import torch
import torch.nn as nn
## create a linear layer:2 x 4 matrix
linear_layer = nn.Linear(4, 2, bias=False) #4 feature input, and 2 output
print(linear_layer.weight) #random generating weight
## assign weight
weights = torch.Tensor([
    [2,2,2,2],
    [2,2,2,2]]
    )
linear_layer.weight = nn.Parameter(weights)
print("Weights:",linear_layer.weight)
input = torch.ones((2,4)) #make it simple
print(input.shape,"\n","Input:","\n",input)
output = linear_layer(input)
print(output.shape,"\n","output:","\n",output)

Parameter containing:
tensor([[ 0.2777,  0.0270,  0.0864,  0.2771],
        [-0.1814, -0.1613,  0.4828,  0.3993]], requires_grad=True)
Weights: Parameter containing:
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.]], requires_grad=True)
torch.Size([2, 4]) 
 Input: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([2, 2]) 
 output: 
 tensor([[8., 8.],
        [8., 8.]], grad_fn=<MmBackward0>)
