<a href="https://colab.research.google.com/github/sardear/TorchNN/blob/main/TorchNN_Pooling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
## Max pooling
## 主要参数
## kernel size:3x3,5x5,..取max的区域大小
## stride:步长，预设kernel size
import torch
import torch.nn as nn
m = nn.MaxPool2d(kernel_size=3, stride=1, padding=0, dilation=1) #可修改padding=1或者dilation=2看看效果
input = torch.randn((5,5))
input = input.unsqueeze(0) #必须包含batch
output = m(input)
print(input)
print(output)

tensor([[[ 2.7040,  0.2313,  0.3785,  1.9474, -0.7484],
         [-0.3140, -0.3340,  1.5712, -2.1298,  0.5638],
         [ 0.8799,  0.1033, -0.2813, -0.0692, -1.4321],
         [ 1.1635, -0.8883,  0.2899,  1.5491,  1.7248],
         [-2.2833,  0.1215,  0.4872,  1.2655,  1.8281]]])
tensor([[[2.7040, 1.9474, 1.9474],
         [1.5712, 1.5712, 1.7248],
         [1.1635, 1.5491, 1.8281]]])


In [17]:
## Average pooling
## 主要参数
## kernel size:3x3,5x5,..取max的区域大小
## stride:步长，预设kernel size
import torch
import torch.nn as nn
m = nn.AvgPool2d(kernel_size=3, stride=1, padding=0) #可修改stride=2, padding=1看看效果
input = torch.ones((5,5))
# input = torch.randn((5,5))
input = input.unsqueeze(0)
output = m(input)
print(input)
print(output)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
