<a href="https://colab.research.google.com/github/sardear/TorchNN/blob/main/TorchNN_ConvLayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Torch Conv2d:example checkt weights
import torch
import torch.nn as nn

c1 = nn.Conv2d(3,1,3, stride=1) #input:3,output:1,kernel:3
# c1 = nn.Conv2d(3,2,3, stride=1) #input:3,output:1,kernel:3
print("C1 weights:",c1.weight.shape) #show weights
print(c1.weight)

input = torch.randn(1,3,5,5) #input image:3x5x5
# 5x5 image: conv2d by 3x3 kernel stride=1 ==> 3x3
print("Input:")
print(input)

output = c1(input) #convolution 2d
print("Output:") #output feature map: 1x3x3
print(output)

C1 weights: torch.Size([1, 3, 3, 3])
Parameter containing:
tensor([[[[-1.8834e-01,  4.1614e-02, -3.8510e-02],
          [ 1.2210e-01, -1.3540e-01, -1.0622e-01],
          [-7.7796e-05, -3.8769e-02,  1.5284e-01]],

         [[ 1.5729e-01, -5.9668e-02, -1.3105e-02],
          [ 1.5899e-01, -1.4271e-01,  8.8917e-02],
          [ 4.8373e-02,  1.1290e-01, -5.4788e-02]],

         [[ 4.2833e-02, -1.5918e-01, -1.0220e-01],
          [ 5.5627e-02, -8.1208e-02, -1.1155e-01],
          [ 1.6570e-01,  1.8301e-02,  5.2337e-02]]]], requires_grad=True)
Input:
tensor([[[[ 0.1660, -0.3331,  0.1576,  0.6322, -0.3814],
          [ 1.7974, -0.2649,  0.9911, -0.6316,  0.2736],
          [ 2.5167,  0.8752,  0.0710,  0.7472, -0.1425],
          [-0.1590,  0.6963,  1.6341,  0.0304, -0.7747],
          [ 0.1821,  1.0957,  0.8224, -0.1910,  2.2198]],

         [[-2.1050, -0.1817, -0.9966, -0.9093, -0.3970],
          [-0.9138, -0.1144,  0.5558,  1.1812, -2.1992],
          [ 0.2768, -1.2767, -0.7687,  0.6505, 

In [ ]:
## Conv2D:set Weights
import torch
import torch.nn as nn
# create a 3 channel 5x5 imagae
image = torch.ones((1,3,5,5))
# create a conv2d:set bias False
c1 = nn.Conv2d(in_channels=3,out_channels=1,kernel_size=3,stride=1,bias=False)
# get weight of kernel
w1 = c1.weight
print(w1.shape,w1)
# set weights
c1.weight = nn.Parameter(torch.ones_like(w1),requires_grad=True) #default:True
print(c1.weight.shape,c1.weight)
fm = c1(image)
print("Feature map:")
print(fm)

torch.Size([1, 3, 3, 3]) Parameter containing:
tensor([[[[-0.1278, -0.0867,  0.0600],
          [-0.0684,  0.1427,  0.0456],
          [ 0.0442,  0.1677,  0.0103]],

         [[-0.1297, -0.0785, -0.0511],
          [ 0.0303,  0.0210,  0.1788],
          [ 0.1321,  0.0152, -0.1081]],

         [[-0.0117,  0.0349,  0.0947],
          [-0.0793,  0.0963,  0.0187],
          [ 0.1436, -0.0716,  0.0755]]]], requires_grad=True)
torch.Size([1, 3, 3, 3]) Parameter containing:
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)
Feature map:
tensor([[[[27., 27., 27.],
          [27., 27., 27.],
          [27., 27., 27.]]]], grad_fn=<ConvolutionBackward0>)


In [ ]:
import torch
import torch.nn.functional as F
# create a filter
filter = torch.ones((1,3,3))
filter = filter*0.33333
filter = torch.cat((filter,filter,filter), dim=0)
filter = torch.unsqueeze(filter, 0)
print(filter,filter.size()) #1,3,3,3
# create a 3 channel 5x4 image
c1 = torch.ones((1,5,5), dtype=torch.float32)
c2 = torch.ones((1,5,5), dtype=torch.float32)*2
c3 = torch.ones((1,5,5), dtype=torch.float32)*3
print(c1)
print(c2)
print(c3)
x = torch.cat((c1,c2,c3),dim=0)
print(x)
print(x.shape) #or .size()
x = torch.unsqueeze(x,0)
print(x)
print(x.shape) #or .size()
output = F.conv2d(x, filter, padding=0, groups=1)
print(output, output.size())

tensor([[[[0.3333, 0.3333, 0.3333],
          [0.3333, 0.3333, 0.3333],
          [0.3333, 0.3333, 0.3333]],

         [[0.3333, 0.3333, 0.3333],
          [0.3333, 0.3333, 0.3333],
          [0.3333, 0.3333, 0.3333]],

         [[0.3333, 0.3333, 0.3333],
          [0.3333, 0.3333, 0.3333],
          [0.3333, 0.3333, 0.3333]]]]) torch.Size([1, 3, 3, 3])
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])
tensor([[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]]])
tensor([[[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]]])
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[2., 2.

`nn.Conv2d`的功能是对由多个输入平面组成的输入信号进行二维卷积。经过卷积后的图像尺寸计算公式为：`N = (W − F + 2P )/S+1`，其中`W`为原始图像大小，`F`为卷积核尺寸，`P`为`padding`大小，`S`是步长。`nn.ConvTranspose2d`的功能是进行反卷积操作，它可以将输入张量的尺寸扩大一定的倍数，并在扩大的同时填充一些值。与卷积层不同的是，反卷积层需要设置更多的超参数，例如输出大小、卷积核大小、步幅和填充。反卷积操作的输出尺寸计算公式为：`N = (W - 1) * S - 2P + F`，其中`W`为输入的尺寸，`F`为卷积核的大小，`P`是填充大小，`S`是步幅。需要注意的是，反卷积层的输出大小与卷积层的输入大小相同，因此反卷积层通常用于上采样操作。

In [8]:
## conv2dTranspose example in Torch
import torch.nn as nn
import torch
# create input tensor
input = torch.randn(1, 1, 5, 5)
print(input.shape,"\n",input)
downsample = nn.Conv2d(1, 2, 3, stride=2, padding=1)
upsample = nn.ConvTranspose2d(2, 1, 3, stride=2, padding=1)
h = downsample(input)
print(h.shape,"\n",h)
out = upsample(h, output_size=input.size()) #还原，最好指定output_size
print(out.size(),"\n",out)

torch.Size([1, 1, 5, 5]) 
 tensor([[[[-0.4281,  0.4371, -0.3488,  0.6858,  1.7134],
          [-1.0266,  0.0559, -0.5841,  0.4120, -1.0775],
          [ 1.0788,  0.5567, -0.6487, -0.1753,  1.2828],
          [-0.1243, -0.2857,  1.0360, -1.2395, -1.1020],
          [ 0.2040,  1.0965,  2.2341,  1.2034,  1.3249]]]])
torch.Size([1, 2, 3, 3]) 
 tensor([[[[ 0.2368,  0.0629,  0.8463],
          [ 0.3956, -0.6668,  0.4095],
          [ 0.0515,  0.3718,  0.5039]],

         [[-0.2204, -0.1264, -0.3743],
          [-0.4845,  0.4811, -0.3077],
          [-0.3359, -0.3673, -0.3157]]]], grad_fn=<ConvolutionBackward0>)
torch.Size([1, 1, 5, 5]) 
 tensor([[[[ 0.0045, -0.0778, -0.0047, -0.3624,  0.0907],
          [-0.3496,  0.2674,  0.2607, -0.2546, -0.5288],
          [-0.0420,  0.3170,  0.0223, -0.0847,  0.0154],
          [-0.3502,  0.0426,  0.1645, -0.4188, -0.3992],
          [-0.0717, -0.2022, -0.0112, -0.2929,  0.0337]]]],
       grad_fn=<ConvolutionBackward0>)
